// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/main-menu/Arcade.tsx": () => import("../components/mockups/main-menu/Arcade.tsx"),
  "./components/mockups/main-menu/Current.tsx": () => import("../components/mockups/main-menu/Current.tsx"),
  "./components/mockups/main-menu/Noir.tsx": () => import("../components/mockups/main-menu/Noir.tsx"),
  "./components/mockups/main-menu/Propaganda.tsx": () => import("../components/mockups/main-menu/Propaganda.tsx")
};
